trustbloc/edge-core

.codecov.yaml
.gitignore
.golangci.yml
LICENSE
Makefile
ci/azp-dependencies.yml
ci/azure-pipelines.yml
doc.go
go.mod
go.sum
pkg/storage/memstore/memstore.go
pkg/storage/memstore/memstore_test.go
pkg/storage/mockstore/mockstore.go
pkg/storage/store.go
scripts/check_license.sh
scripts/check_lint.sh
scripts/check_unit.sh

feat: In-Memory Store and Mock Store

---

pkg/storage/mockstore/mockstore.go

Fixed a comment that was being flagged by the linter.

fix: Corrected comment

---

pkg/storage/memstore/memstore.go

fix: MemStore is now thread-safe

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/memstore/memstore.go
pkg/storage/memstore/memstore_test.go
pkg/storage/store.go

Also fixed an erroneous comment in store.go.

refactor: Prevent creation of duplicate store and return custom error

---

pkg/storage/mockstore/mockstore.go

fix: Make MockStore implement Store interface

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go

fix: bug in isJSON function

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go

feat: support update in couchdb

---

ci/azure-pipelines.yml

fix: Upload for Codecov

---

pkg/tls/certpool.go
pkg/tls/certpool_test.go

feat: Add tls certpool

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/memstore/memstore.go
pkg/storage/memstore/memstore_test.go
pkg/storage/mockstore/mockstore.go
pkg/storage/store.go

Signed-off-by: Derek Trider <Derek.Trider@securekey.com
closes #20

feat: Index and query support

---

pkg/storage/couchdb/couchdbstore.go

chore: Get rev ID from couchdb

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go

feat: Add couchdb prefix

---

pkg/utils/retry/example_test.go
pkg/utils/retry/retry.go
pkg/utils/retry/retry_test.go

feat: Generic retry mechanism

---

go.mod
go.sum
pkg/internal/logging/metadata/callerInfo.go
pkg/internal/logging/metadata/callerInfo_test.go
pkg/internal/logging/metadata/level.go
pkg/internal/logging/metadata/level_test.go
pkg/internal/logging/metadata/opts.go
pkg/internal/logging/metadata/opts_test.go
pkg/internal/logging/metadata/util_test.go
pkg/internal/logging/metadata/utils.go
pkg/internal/logging/modlog/deflog.go
pkg/internal/logging/modlog/deflog_test.go
pkg/internal/logging/modlog/logapi.go
pkg/internal/logging/modlog/logtestutils.go
pkg/internal/logging/modlog/modlog.go
pkg/internal/logging/modlog/modlog_test.go
pkg/log/api.go
pkg/log/logger.go
pkg/log/logger_test.go
pkg/log/provider.go
pkg/log/provider_test.go

feat: Logger

---

go.mod
go.sum
pkg/storage/memstore/memstore.go
pkg/storage/memstore/memstore_test.go
pkg/storage/mysql/mysqlstore.go
pkg/storage/mysql/mysqlstore_test.go
pkg/storage/store.go
scripts/check_unit.sh

closes #35
Create Index will be addressed in the separate #36 
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

feat: Mysql storage support

---

pkg/internal/support/httphandler.go
pkg/internal/support/httphandler_test.go
pkg/restapi/internal/common/http/common.go
pkg/restapi/logspec/controller.go
pkg/restapi/logspec/controller_test.go
pkg/restapi/logspec/operation/openapi.go
pkg/restapi/logspec/operation/operations.go
pkg/restapi/logspec/operation/operations_test.go

feat: Importable, generic handlers for getting and changing log levels

---

pkg/restapi/logspec/operation/openapi.go

fix: Added missing emptyRes model

---

pkg/storage/mysql/mysqlstore.go
pkg/storage/mysql/mysqlstore_test.go

closes #36 
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

feat: Create index support in mysql

---

go.mod
go.sum
pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/memstore/memstore_test.go
pkg/tls/certpool.go

Signed-off-by: Derek Trider <derek.trider@securekey.com>

refactor: Remove remaining Logrus references

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/memstore/memstore.go
pkg/storage/memstore/memstore_test.go
pkg/storage/mockstore/mockstore.go
pkg/storage/mysql/mysqlstore.go
pkg/storage/mysql/mysqlstore_test.go
pkg/storage/store.go

closes #45 
Signed-off-by: Derek Trider <derek.trider@securekey.com>

feat: Store delete method

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/couchdb/errors.go
pkg/storage/errors.go
pkg/storage/memstore/memstore_test.go
pkg/storage/mysql/errors.go
pkg/storage/mysql/mysqlstore.go
pkg/storage/mysql/mysqlstore_test.go
pkg/storage/store.go

closes #52
- Wrapped errors
- Improved error messages
- Removed unused const
- Removed duplicate code
- Reorganized order of functions
Signed-off-by: Derek Trider <derek.trider@securekey.com>

refactor: Provider and storage

---

pkg/storage/mysql/mysqlstore.go

closes #55
Signed-off-by: Derek Trider <derek.trider@securekey.com>

fix: potential for error to be overwritten

---

pkg/log/provider.go
pkg/log/provider_test.go
pkg/storage/couchdb/couchdbstore_test.go

closes #56
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>

fix: Don't enforce logging levels for custom logger

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go

fix: CouchDBStore GetAll call returns design documents

---

pkg/log/mocklogger/mocklogger.go
pkg/storage/couchdb/couchdbstore_test.go

feat: Mock logger

---

pkg/storage/mysql/mysqlstore.go

need to guard against special characters in object identifiers
closes #73
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

fix: mysql store: need to guard against special characters

---

pkg/storage/couchdb/couchdbstore_test.go

This check ensures that we are properly logging this important warning message.

fix: Added log check to CouchDB index unit test

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/couchdb/errors.go

Signed-off-by: Grace Liu <grace.liu@securekey.com>
Closes: #81

fix: allows deleted documents to be stored again

---

.gitignore
pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/couchdb/errors.go
scripts/check_unit.sh

#Closes #83 
Signed-off-by: Grace Liu <grace.liu@securekey.com>

feat: performs readiness check on couchdb instance

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/couchdb/errors.go
scripts/check_unit.sh
scripts/couchdb-config/config.ini

#Closes #70 
Signed-off-by: Grace Liu <grace.liu@securekey.com>

fix: couchDB checks for existence of '_users' db in ping

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go

Signed-off-by: Grace Liu <grace.liu@securekey.com>

fix: couchdb store ignore 'deleted' error

---

pkg/zcapld/create.go
pkg/zcapld/create_test.go
pkg/zcapld/zcap.go

closes #97 
Signed-off-by: George Aristy <george.aristy@securekey.com>

feat: #97 zcapld: create API

---

pkg/zcapld/didkey_test.go
pkg/zcapld/resolve.go
pkg/zcapld/resolve_test.go

closes #98 
Signed-off-by: George Aristy <george.aristy@securekey.com>

feat: #98 zcapld: support did:key

---

go.mod
go.sum
pkg/zcapld/middleware.go
pkg/zcapld/middleware_test.go

closes #101 
Signed-off-by: George Aristy <george.aristy@securekey.com>

feat: #101 zcaps - middleware

---

pkg/utils/cmd/util.go
pkg/utils/cmd/util_test.go

feat: add cmd method to get optional arg

---

go.mod
go.sum
pkg/zcapld/resolve.go

chore: update aries-framework-go revision

---

go.mod
go.sum

chore: update aries revision

---

pkg/storage/couchdb/couchdbstore.go
pkg/storage/couchdb/couchdbstore_test.go
pkg/storage/errors.go
pkg/storage/mysql/mysqlstore.go
pkg/storage/mysql/mysqlstore_test.go
pkg/storage/store.go

Allows for pagination of CouchDB query results.

feat: CouchDB query bookmark support

---

pkg/storage/mockstore/mockstore.go

feat: Add ErrPutAll to MockStore

---

go.mod
go.sum

chore: Update aries-framework-go to v0.1.5

---

README.md

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

chore: rename master branch to main

---

pkg/zcapld/create.go
pkg/zcapld/create_test.go

Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>

feat: add support for setting document loader cache

---

go.mod
go.sum

chore: update to latest AFG with X25519 KW in KMS

---

pkg/zcapld/create.go
pkg/zcapld/create_test.go
pkg/zcapld/verify.go
pkg/zcapld/verify_test.go
pkg/zcapld/zcap.go

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

feat: zcap - adds caveat expiry support.

---

pkg/zcapld/didkey_test.go
pkg/zcapld/middleware.go
pkg/zcapld/middleware_test.go
pkg/zcapld/resolve.go
pkg/zcapld/resolve_test.go

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

feat: Zcap - trustbloc did support

---

pkg/zcapld/middleware.go
pkg/zcapld/middleware_test.go
pkg/zcapld/util_test.go

Exposes functions to prevent duplicates in other places.
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

feat: Zcap - exposes CompressZCAP/DecompressZCAP functions

---

go.mod
go.sum

chore: update latest AFG revision

---

go.mod
go.sum

chore: Update aries-framework-go to v0.1.6

---

go.mod
go.sum
pkg/zcapld/middleware.go

chore: update to aries revision 7ec3a2c4697c512726ffaa4143e56491405dd828

---

go.mod
go.sum

Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

chore: update aries

---

go.mod
go.sum

Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

chore: update afgo version

---

go.mod
go.sum

Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>

chore: update AFGO

---

pkg/log/logger.go
pkg/log/logger_test.go
pkg/restapi/logspec/operation/operations.go
pkg/restapi/logspec/operation/operations_test.go

The code that sets the logging spec was moved from the REST API to the logger itself so that the logging spec may be set programmatically.
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>

refactor: Expose function to set logging spec

---

go.mod
go.sum

chore: update latest afgo

---

go.mod
go.sum

chore: update to latest afgo with didcomm v2 support

---

ci/azure-pipelines.yml
go.mod
go.sum
scripts/check_unit.sh

chore: updated go to 1.17 and latest afgo commit

---

go.mod
go.sum

chore: latest afgo commit

---

go.mod
go.sum

chore: update AFGO to v0.1.18
